name: steel_soldier
description: Tactical fitness app for soldiers and combat athletes
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9

  # Authentication & Security
  local_auth: ^2.1.7
  flutter_secure_storage: ^9.2.4
  biometric_storage: ^5.0.2

  # Networking, Storage, Config
  http: ^1.4.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.2
  intl: ^0.20.2

  # UI & Visualization
  google_fonts: ^6.2.1
  fl_chart: ^1.0.0
  provider: ^6.1.2
  flutter_local_notifications: ^19.2.1
  url_launcher: ^6.2.5

  # Document Generation
  pdf: ^3.10.6
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/deadlift.png
    - assets/images/power_throw.png
    - assets/images/pushup.png
    - assets/images/sprint_drag.png
    - assets/images/plank.png
    - assets/images/run.png
    - assets/icons/
