name: steel_soldier
description: Tactical fitness app for soldiers and combat athletes
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  local_auth: ^2.1.7
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8

  # Storage & Security
  flutter_secure_storage: ^9.2.4
  biometric_storage: ^5.0.2

  # Data & HTTP
  http: ^1.4.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2

  # UI
  google_fonts: ^6.2.1
  fl_chart: ^1.0.0
  provider: ^6.1.2
  flutter_local_notifications: ^17.1.0
  url_launcher: ^6.2.5

  # Env support
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/deadlift.png
    - assets/images/power_throw.png
    - assets/images/pushup.png
    - assets/images/sprint_drag.png
    - assets/images/plank.png
    - assets/images/run.png
    - assets/icons/
